### ISSUE TITLE
Problem parsing blif file

### ISSUE THREAD

**Issue by lfigiel** [cliffordwolf/yosys#417] opened 2017-09-25 19:57 UTC
Is it a problem with yosys or arachne-pnr ?
[cseed/arachne-pnr#75](https://github.com/cseed/arachne-pnr/issues/75)

**Comment by cliffordwolf** [comment] 2017-09-26 11:36
What's your input? What's your script? It can't reproduce this without this information.

See also Q1 in the [Yosys FAQ](http://www.clifford.at/yosys/faq.html).

**Comment by cliffordwolf** [comment] 2017-09-26 12:16
I'm closing this a a possible dup of #404.

**Closed by cliffordwolf** 2017-09-26 12:16 UTC

**Comment by lfigiel** [comment] 2017-09-26 12:40
Attached, please find the source code
[top.zip](https://github.com/cliffordwolf/yosys/files/1333115/top.zip)
To reproduce the issue:
yosys -q -p "synth_ice40 -blif top.blif" top.v
arachne-pnr -d 1k -P vq100 -p iceblink40.pcf top.blif -o top.txt

Please note that the code works perfectly in iCEcube2 for the same platform (iCE40).

**Comment by lfigiel** [comment] 2017-09-26 12:44
So my understanding is that yosys's output uses something that is not present in the hardware - hence the error unknown model `$DFFSR_PPP' but somehow iCEcube2 finds the way to synthesis same code for the same platform.

**Comment by cliffordwolf** [comment] 2017-09-26 12:47
Did you read the explanation in #404 that I linked to? I explained how they do it there.

**Comment by lfigiel** [comment] 2017-09-26 13:02
Yes, I did, it is all clear now, thank you. I will try to re-write the code to avoid using missing components.
