### ISSUE TITLE
Autotest.sh and casex

### ISSUE THREAD

**Issue by Kmanfi** [cliffordwolf/yosys#205] opened 2016-08-18 10:04 UTC
Hi, I sent this case to your private email.

**Comment by cliffordwolf** [comment] 2016-08-18 11:46
The problem is that the net you are using as expression in `casex(expr)` is undefined (x). Here is essentially what is happening:

```
module casex_test(out, in);
  output reg out;
  input in;
  wire sel = 'bx;
  always @* begin
    casex (sel)
      1'b0:
        out = 0;
      default:
        out = in;
    endcase
  end
endmodule
```

Even with `prep -ifx`, this is something that cannot be modeled by yosys at the moment. (As it is custom for synthesis tools in general, see sec *5.5 Support for values x and z* of IEEE Std. 1364.1(E):2002.)

However, the reason `sel` (i.e. the `cas_selector` signal in your original code) was `'bx` is because there was a bug in the testbench generator used by autotest.sh. I have now fixed this bug in commit b3a0145.

**Closed by cliffordwolf** 2016-08-18 11:46 UTC
