### ISSUE TITLE
Got Problem with building HEAD

### ISSUE THREAD

**Issue by SpaceCowboyMax** [cliffordwolf/yosys#256] opened 2016-11-01 08:22 UTC
Cent OS
All dependencies are installed?
`[  0%] Building frontends/verilog/verilog_parser.tab.cc
frontends/verilog/verilog_parser.y:139.9-19: error: %define variable 'parse.error' is not used
make: *** [frontends/verilog/verilog_parser.tab.cc] Error 1`

**Comment by cliffordwolf** [comment] 2016-11-01 08:45
This is a duplicate of #224.

Update to bison 3 or remove the following two lines from verilog_parser.y:

```
%define parse.error verbose
%define parse.lac full
```

**Closed by cliffordwolf** 2016-11-01 08:45 UTC
