### ISSUE TITLE
Segmentation Fault with modified `demo2.v` from `examples/smtbmc`

### ISSUE THREAD

**Issue by cr1901** [cliffordwolf/yosys#444] opened 2017-10-25 23:37 UTC
I was modifying `demo2.v` from `yosys`' `examples/smtbmc` directory, when I discovered an input verilog file and commands which crash `yosys` with a Segmentation Fault. This crash is reproducible on both Windows and Linux.

First, the sample file:
```
// Nothing to prove in this demo.
// Just an example for memories, vcd dumps and vlog testbench dumps.

`ifdef FORMAL
`define assume(_expr_) assume(_expr_)
`else
`define assume(_expr_)
`endif

module demo2(input clk, input [4:0] addr, output reg [31:0] data);
	reg [31:0] mem [0:31];
	always @(posedge clk)
		data <= mem[addr];

	reg [31:0] used_addr = 0;
	reg [31:0] used_dbits = 0;
	reg initstate = 1;

    always @(posedge clk) begin
        initstate <= 1;

        if (!initstate) begin
            `assume(data != 0);
            `assume((used_dbits & data) == 0);
        end
    end
endmodule
```

This is a _contrived_ minimal example to reproduce the crash. I don't think it makes sense to simulate/verify/synthesize as-is.

Next the command invocation (`./yosys -p 'read_verilog -formal test.v; prep -top demo2'`):
```
 /----------------------------------------------------------------------------\
 |                                                                            |
 |  yosys -- Yosys Open SYnthesis Suite                                       |
 |                                                                            |
 |  Copyright (C) 2012 - 2016  Clifford Wolf <clifford@clifford.at>           |
 |                                                                            |
 |  Permission to use, copy, modify, and/or distribute this software for any  |
 |  purpose with or without fee is hereby granted, provided that the above    |
 |  copyright notice and this permission notice appear in all copies.         |
 |                                                                            |
 |  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES  |
 |  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF          |
 |  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR   |
 |  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    |
 |  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN     |
 |  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF   |
 |  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.            |
 |                                                                            |
 \----------------------------------------------------------------------------/

 Yosys 0.7+361 (git sha1 1170508, gcc 5.4.0-6ubuntu1~16.04.4 -fPIC -Os)


-- Running command `read_verilog -formal test.v; prep -top demo2' --

1. Executing Verilog-2005 frontend.
Parsing formal Verilog input from `test.v' to AST representation.
Generating RTLIL representation for module `\demo2'.
Successfully finished Verilog frontend.

2. Executing PREP pass.

2.1. Executing HIERARCHY pass (managing design hierarchy).

2.1.1. Analyzing design hierarchy..
Top module:  \demo2

2.1.2. Analyzing design hierarchy..
Top module:  \demo2
Removed 0 unused modules.
Module demo2 directly or indirectly contains $assert cells -> setting "keep" attribute.

2.2. Executing PROC pass (convert processes to netlists).

2.2.1. Executing PROC_CLEAN pass (remove empty switches from decision trees).
Cleaned up 0 empty switches.

2.2.2. Executing PROC_RMDEAD pass (remove dead branches from decision trees).
Removed a total of 0 dead cases.

2.2.3. Executing PROC_INIT pass (extract init attributes).
Found init rule in `\demo2.$proc$test.v:24$21'.
  Set init value: $formal$test.v:24$2_EN = 1'0
Found init rule in `\demo2.$proc$test.v:23$19'.
  Set init value: $formal$test.v:23$1_EN = 1'0
Found init rule in `\demo2.$proc$test.v:17$18'.
  Set init value: \initstate = 1'1

2.2.4. Executing PROC_ARST pass (detect async resets in processes).

2.2.5. Executing PROC_MUX pass (convert decision trees to multiplexers).
Creating decoders for process `\demo2.$proc$test.v:24$21'.
     1/1: $0$formal$test.v:24$2_EN[0:0]$22
Creating decoders for process `\demo2.$proc$test.v:23$19'.
     1/1: $0$formal$test.v:23$1_EN[0:0]$20
Creating decoders for process `\demo2.$proc$test.v:17$18'.
     1/1: $1\initstate[0:0]
Creating decoders for process `\demo2.$proc$test.v:16$17'.
     1/1: $0\used_dbits[31:0]
Creating decoders for process `\demo2.$proc$test.v:15$16'.
     1/1: $0\used_addr[31:0]
Creating decoders for process `\demo2.$proc$test.v:19$5'.
     1/5: $0\initstate[0:0]
     2/5: $0$formal$test.v:23$1_EN[0:0]$7
     3/5: $0$formal$test.v:23$1_CHECK[0:0]$6
     4/5: $0$formal$test.v:24$2_EN[0:0]$9
     5/5: $0$formal$test.v:24$2_CHECK[0:0]$8
Creating decoders for process `\demo2.$proc$test.v:12$3'.
     1/1: $0\data[31:0]

2.2.6. Executing PROC_DLATCH pass (convert process syncs to latches).
No latch inferred for signal `\demo2.\used_dbits' from process `\demo2.$proc$test.v:16$17'.
No latch inferred for signal `\demo2.\used_addr' from process `\demo2.$proc$test.v:15$16'.

2.2.7. Executing PROC_DFF pass (convert process syncs to FFs).
Creating register for signal `\demo2.\initstate' using process `\demo2.$proc$test.v:19$5'.
  created $dff cell `$procdff$35' with positive edge clock.
Creating register for signal `\demo2.$formal$test.v:23$1_CHECK' using process `\demo2.$proc$test.v:19$5'.
  created $dff cell `$procdff$36' with positive edge clock.
Creating register for signal `\demo2.$formal$test.v:23$1_EN' using process `\demo2.$proc$test.v:19$5'.
  created $dff cell `$procdff$37' with positive edge clock.
Creating register for signal `\demo2.$formal$test.v:24$2_CHECK' using process `\demo2.$proc$test.v:19$5'.
  created $dff cell `$procdff$38' with positive edge clock.
Creating register for signal `\demo2.$formal$test.v:24$2_EN' using process `\demo2.$proc$test.v:19$5'.
  created $dff cell `$procdff$39' with positive edge clock.
Creating register for signal `\demo2.\data' using process `\demo2.$proc$test.v:12$3'.
  created $dff cell `$procdff$40' with positive edge clock.

2.2.8. Executing PROC_CLEAN pass (remove empty switches from decision trees).
Removing empty process `demo2.$proc$test.v:24$21'.
Removing empty process `demo2.$proc$test.v:23$19'.
Removing empty process `demo2.$proc$test.v:17$18'.
Removing empty process `demo2.$proc$test.v:16$17'.
Removing empty process `demo2.$proc$test.v:15$16'.
Found and cleaned up 1 empty switch in `\demo2.$proc$test.v:19$5'.
Removing empty process `demo2.$proc$test.v:19$5'.
Removing empty process `demo2.$proc$test.v:12$3'.
Cleaned up 1 empty switch.

2.3. Executing OPT_EXPR pass (perform const folding).
Replacing $ne cell `$ne$test.v:23$11' in module `demo2' with $logic_not.
Replacing $eq cell `$eq$test.v:24$13' in module `demo2' with $logic_not.
Optimizing away select inverter for $mux cell `$procmux$24' in module `demo2'.
Optimizing away select inverter for $mux cell `$procmux$27' in module `demo2'.
Optimizing away select inverter for $mux cell `$procmux$30' in module `demo2'.
Optimizing away select inverter for $mux cell `$procmux$33' in module `demo2'.

2.4. Executing OPT_CLEAN pass (remove unused cells and wires).
Finding unused cells or wires in module \demo2..
  removing unused `$logic_not' cell `$logic_not$test.v:22$10'.
  removing unused non-port wire \used_dbits.
  removing unused non-port wire \used_addr.
  removed 18 unused temporary wires.
Removed 1 unused cells and 18 unused wires.

2.5. Executing CHECK pass (checking for obvious problems).
checking module demo2..
found and reported 0 problems.

2.6. Executing OPT pass (performing simple optimizations).

2.6.1. Executing OPT_EXPR pass (perform const folding).

2.6.2. Executing OPT_MERGE pass (detect identical cells).
Finding identical cells in module `\demo2'.
Removed a total of 0 cells.

2.6.3. Executing OPT_MUXTREE pass (detect dead branches in mux trees).
Running muxtree optimizer on module \demo2..
  Creating internal representation of mux trees.
  Evaluating internal representation of mux trees.
    Root of a mux tree: $procmux$24 (pure)
    Root of a mux tree: $procmux$27 (pure)
    Root of a mux tree: $procmux$30 (pure)
    Root of a mux tree: $procmux$33 (pure)
  Analyzing evaluation results.
Removed 0 multiplexer ports.

2.6.4. Executing OPT_REDUCE pass (consolidate $*mux and $reduce_* inputs).
  Optimizing cells in module \demo2.
Performed a total of 0 changes.

2.6.5. Executing OPT_MERGE pass (detect identical cells).
Finding identical cells in module `\demo2'.
  Cell `$procmux$30' is identical to cell `$procmux$24'.
    Redirecting output \Y: $0$formal$test.v:24$2_EN[0:0]$9 = $0$formal$test.v:23$1_EN[0:0]$7
    Removing $mux cell `$procmux$30' from module `\demo2'.
  Cell `$procdff$39' is identical to cell `$procdff$37'.
    Redirecting output \Q: $formal$test.v:24$2_EN = $formal$test.v:23$1_EN
    Removing $dff cell `$procdff$39' from module `\demo2'.
Removed a total of 2 cells.

2.6.6. Executing OPT_RMDFF pass (remove dff with constant values).
Removing $procdff$35 ($dff) from module demo2.
Replaced 1 DFF cells.

2.6.7. Executing OPT_CLEAN pass (remove unused cells and wires).
Finding unused cells or wires in module \demo2..
  removing unused non-port wire \initstate.
  removed 2 unused temporary wires.
  removing redundent init attribute on $formal$test.v:24$2_EN.
  removed 1 unused temporary wires.
Removed 1 unused cells and 21 unused wires.

2.6.8. Executing OPT_EXPR pass (perform const folding).
Replacing $mux cell `$procmux$24' (1) in module `\demo2' with constant driver `$0$formal$test.v:23$1_EN[0:0]$7 = 1'0'.
Replacing $mux cell `$procmux$27' (1) in module `\demo2' with constant driver `$0$formal$test.v:23$1_CHECK[0:0]$6 = 1'x'.
Replacing $mux cell `$procmux$33' (1) in module `\demo2' with constant driver `$0$formal$test.v:24$2_CHECK[0:0]$8 = 1'x'.

2.6.9. Rerunning OPT passes. (Maybe there is more to do..)

2.6.10. Executing OPT_MUXTREE pass (detect dead branches in mux trees).
Running muxtree optimizer on module \demo2..
  Creating internal representation of mux trees.
  No muxes found in this module.
Removed 0 multiplexer ports.

2.6.11. Executing OPT_REDUCE pass (consolidate $*mux and $reduce_* inputs).
  Optimizing cells in module \demo2.
Performed a total of 0 changes.

2.6.12. Executing OPT_MERGE pass (detect identical cells).
Finding identical cells in module `\demo2'.
  Cell `$procdff$38' is identical to cell `$procdff$36'.
    Redirecting output \Q: $formal$test.v:24$2_CHECK = $formal$test.v:23$1_CHECK
    Removing $dff cell `$procdff$38' from module `\demo2'.
  Cell `$assume$test.v:24$15' is identical to cell `$assume$test.v:23$14'.
    Removing $assume cell `$assume$test.v:24$15' from module `\demo2'.
Removed a total of 2 cells.

2.6.13. Executing OPT_RMDFF pass (remove dff with constant values).
Removing $procdff$36 ($dff) from module demo2.
Removing $procdff$37 ($dff) from module demo2.
Segmentation Fault (core dumped)
```

Lastly when dumping the log to a file on Linux, I get this on the console (guessing an exception wasn't catched that was supposed to be?):

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  dict::at()
Aborted (core dumped)
```

**Comment by cliffordwolf** [comment] 2017-10-26 13:35
Some kind of weird memory corruption.. I'm looking into it now.

Some notes for the record below. Feel free to ignore.

----

Minimal script to reproduce:
```
read_verilog -formal test.v; hierarchy; proc_init; proc_mux; proc_dff; proc_clean
opt_clean; opt_merge; opt_rmdff; opt_clean; opt_expr; opt_rmdff
```

Looks like a `Wire*` being deleted while still in use. Not sure if the bug even is in `opt_rmdff` or much earlier. The `std::out_of_range` exception is thrown by a method of a deleted container accessing freed data on the heap.

**Comment by cliffordwolf** [comment] 2017-10-26 16:12
Fixed in c238f45. Thanks for reporting this issue.

**Closed by cliffordwolf** 2017-10-26 16:12 UTC
