### ISSUE TITLE
Related to #134

### ISSUE THREAD

**Issue by Kmanfi** [cliffordwolf/yosys#135] opened 2016-03-24 11:42 UTC
Same thing with reg as with wire.

```
module task_bug ( in_data, do );

   input [15:0] in_data;                
   output [15:0]  do;
   reg [15:0] out_data;                     

   assign do = out_data;

   always @ (*)
     begin

    Test_task(in_data, out_data);
         // out_data = in_data; // This works but above task doesn't

     end

   task Test_task;
      input [15:0]  in_d;
      output [15:0] out_data;

      begin
        out_data = in_d;
      end
   endtask

endmodule
```

**Comment by cliffordwolf** [comment] 2016-03-24 12:33
Are you sure that this is not fixed by 5328a851490588d6162ca0edaad5ed713bc75401, which fixed #134? I for one cannot reproduce any problem in this code with current git head. I'm closing this now. Please re-open if you think there is still a problem.

**Closed by cliffordwolf** 2016-03-24 12:33 UTC
